/**
 * Non-confidential synthetic FR1 reference project — 99 §42.
 *
 * This is the component/project side of the Golden Demo. The network,
 * boundary, analytical result and Screens 08–12 artifacts are built from these
 * authoritative inputs in `demoGoldenFlow.ts`.
 */

import type { Project, Scenario } from '@/domain/project';
import { SCHEMA_VERSION } from '@/domain/project';
import { BUILTIN_TIM_IDS, defaultMaterials } from '@/domain/materials';
import {
  emptyExternalMappings,
  emptyThermalSpec,
  type ArchitectureTemplate,
  type BaseZone,
  type Component,
  type ComponentCategory,
  type ComponentProvenance,
  type LimitType,
  type ModuleReferenceLocation,
  type PackageType,
  type HeatPathType,
} from '@/domain/component';
import type { SourceRevision } from '@/domain/revision';
import { sourced, type SourcedValue, type ThermalDataSource } from '@/domain/sourcedValue';

export const DEMO_PROJECT_ID = 'FR1_RRU_GOLDEN_DEMO';
export const DEMO_SOURCE_PROJECT_ID = 'FR1_COMPONENT_REFERENCE_DEMO';
export const DEMO_SCENARIO_ID = 'SCN_001';
export const DEMO_NETWORK_ID = 'Main Thermal Network';
export const DEMO_TIMESTAMP = '2026-01-15T08:00:00.000Z';

/** Stable fixture identity makes seeded artifacts reproducible across reloads. */
export const DEMO_SOURCE_REVISION: SourceRevision = {
  project_revision: 'rev:project:golden-demo-v1',
  component_revision: 'rev:component:golden-demo-v1',
  solver_input_revision: 'rev:solver_input:golden-demo-v1',
  limit_revision: 'rev:limit:golden-demo-v1',
  network_revision: 'rev:network:golden-demo-v1',
  scenario_revision: 'rev:scenario:golden-demo-v1',
};

export function demoProject(): Project {
  return {
    project_id: DEMO_PROJECT_ID,
    project_name: 'FR1 RRU Golden Demo',
    revision: DEMO_SOURCE_REVISION.project_revision,
    // The demo states its coin size so its RF parts resolve end to end; the
    // rest of the constants are the shipped values.
    materials: {
      ...defaultMaterials(),
      coin_L_mm: { value: 55, source: 'Manual', updated_at: DEMO_TIMESTAMP },
      coin_W_mm: { value: 35, source: 'Manual', updated_at: DEMO_TIMESTAMP },
      coin_thickness_mm: { value: 2.0, source: 'Manual', updated_at: DEMO_TIMESTAMP },
    },
    project_context: {
      customer: 'Synthetic Demo Program',
      owner: 'Thermal Engineering Demo',
      description: 'Non-confidential synthetic FR1 RRU golden-flow validation project',
      product_type: 'RRU',
      deployment: 'Outdoor',
      frequency_range: 'FR1',
      project_stage: 'EVT',
      cooling_architecture: ['Natural Convection', 'Die-casting Fin'],
      enclosure_type: 'Single-sided Cooling',
      // The demo's four zones share one heat sink — the FUNCTIONAL_ZONES shape
      // `demoGoldenFlow` builds.
      base_structure: 'FUNCTIONAL_ZONES',
      notes: [
        'Synthetic engineering fixture only; no customer CAD or test data.',
        'Four thermal zones share one rear heat sink and one ambient boundary.',
        'Analytical results are generated by the product solver during seeding.',
        'FloTHERM remains Deferred and is not required by this workflow.',
      ].join('\n'),
    },
    active_scenario_id: DEMO_SCENARIO_ID,
    status: 'active',
    meta: {
      created_at: DEMO_TIMESTAMP,
      updated_at: DEMO_TIMESTAMP,
      schema_version: SCHEMA_VERSION,
    },
  };
}

export function demoSourceProject(): Project {
  return {
    ...demoProject(),
    project_id: DEMO_SOURCE_PROJECT_ID,
    project_name: 'Synthetic FR1 Component Reference',
    revision: 'rev:project:golden-demo-source-v1',
    active_scenario_id: DEMO_SCENARIO_ID,
    project_context: {
      ...demoProject().project_context,
      description: 'Synthetic component source used to exercise Screen 02 import',
      project_stage: 'Prototype',
      notes: 'Synthetic reference rows with deliberate duplicate names for import testing.',
    },
  };
}

export function demoScenario(projectId = DEMO_PROJECT_ID): Scenario {
  return {
    id: DEMO_SCENARIO_ID,
    project_id: projectId,
    revision:
      projectId === DEMO_PROJECT_ID
        ? DEMO_SOURCE_REVISION.scenario_revision
        : 'rev:scenario:golden-demo-source-v1',
    name: 'Baseline 55C Natural Convection',
    ambient_C: 55,
    wind_mps: 0,
    solar_W_m2: 0,
    power_scale: 1,
    notes: 'Synthetic baseline used by the 01→12 analytical golden flow.',
    is_default: true,
  };
}

function provenance(sourceProjectId: string, sourceProjectName: string): ComponentProvenance {
  return {
    source_type: 'ExistingProject',
    source_project_id: sourceProjectId,
    source_project_name: sourceProjectName,
    source_file: null,
    imported_at: DEMO_TIMESTAMP,
    last_modified_at: DEMO_TIMESTAMP,
    modified_by: 'Golden Demo Seeder',
  };
}

interface Seed {
  id: string;
  name: string;
  category: ComponentCategory;
  qty: number;
  power_W: number;
  r_jc: number | null;
  limit_C: number;
  limit_type: LimitType;
  package_type: PackageType;
  heat_path: HeatPathType;
  heat_path_parameters?: Record<string, number | string | boolean | null>;
  tim: string;
  contact: [number, number];
  /** Left/center/right point on the manufacturer temperature-reference surface. */
  limit_reference_note?: ModuleReferenceLocation;
  /** Installed bond line override; defaults to the demo's normal 0.15 mm. */
  tim_blt_mm?: number;
  template: ArchitectureTemplate;
  zone: BaseZone;
}

function demoSourced<T>(value: T, source: ThermalDataSource, reference: string): SourcedValue<T> {
  return {
    ...sourced(value, source, { confidence: 'high', reference }),
    updated_at: DEMO_TIMESTAMP,
  };
}

function buildReadyComponents(seeds: Seed[]): Component[] {
  return seeds.map((seed) => {
    const spec = emptyThermalSpec();
    return {
      id: seed.id,
      name: seed.name,
      category: seed.category,
      enabled: true,
      qty: seed.qty,
      power_W: demoSourced(seed.power_W, 'Imported', 'Synthetic FR1 Golden Demo power budget'),
      thermal_spec: {
        ...spec,
        limit_type: seed.limit_type,
        // The demo's limits come from (synthetic) datasheets, so the surface
        // they refer to is known rather than inferred.
        limit_type_confirmed: true,
        limit_C: demoSourced(seed.limit_C, 'Datasheet', 'Synthetic component qualification limit'),
        limit_reference_note: seed.limit_reference_note ?? '',
        r_jc_C_per_W:
          seed.r_jc == null
            ? null
            : demoSourced(seed.r_jc, 'Datasheet', 'Synthetic component thermal profile'),
        package_type: seed.package_type,
        geometry: {
          ...spec.geometry,
          package_L_mm:
            seed.heat_path === 'ModuleSurface' ? seed.contact[0] : seed.contact[0] + 2,
          package_W_mm:
            seed.heat_path === 'ModuleSurface' ? seed.contact[1] : seed.contact[1] + 2,
          package_H_mm: 2,
          source_L_mm: seed.heat_path === 'ModuleSurface' ? null : seed.contact[0],
          source_W_mm: seed.heat_path === 'ModuleSurface' ? null : seed.contact[1],
          board_thickness_mm: 1.6,
        },
        heat_path: { type: seed.heat_path, parameters: seed.heat_path_parameters ?? {} },
        // The demo states every heat path deliberately, so none is a guess.
        heat_path_confirmed: true,
        tim: {
          ...spec.tim,
          tim_id: seed.tim,
          // A measured bond line, which is the one thing a component may state.
          blt_mm: demoSourced(
            seed.tim_blt_mm ?? 0.15,
            'Datasheet',
            'Synthetic installed bond-line measurement',
          ),
        },
      },
      architecture_prep: {
        template_preference: seed.template,
        preferred_base_zone: seed.zone,
        qty_model_preference: seed.qty > 1 ? 'INDIVIDUAL' : 'AGGREGATE',
        thermal_profile_status: 'Ready',
      },
      provenance: provenance(DEMO_SOURCE_PROJECT_ID, 'Synthetic FR1 Component Reference'),
      external_mappings: emptyExternalMappings(),
      notes: 'Synthetic Golden Demo component.',
    };
  });
}

/** Exact 99 §42 population: 4 PA, 4 Driver, 1 Filter, 1 FPGA, 1 Power Module. */
export function demoComponents(): Component[] {
  return buildReadyComponents([
    {
      id: 'CMP_FINAL_PA',
      name: 'Final PA',
      category: 'RF',
      qty: 4,
      power_W: 45,
      r_jc: 0.22,
      limit_C: 150,
      limit_type: 'Tj',
      package_type: 'QFN',
      heat_path: 'Coin',
      tim: BUILTIN_TIM_IDS.grease,
      contact: [18, 12],
      template: 'BOTTOM_COOL_COIN',
      zone: 'RF_LEFT',
    },
    {
      id: 'CMP_DRIVER',
      name: 'Driver',
      category: 'RF',
      qty: 4,
      power_W: 8,
      r_jc: 0.55,
      limit_C: 140,
      limit_type: 'Tj',
      package_type: 'QFN',
      heat_path: 'Board',
      tim: BUILTIN_TIM_IDS.pad,
      contact: [8, 8],
      template: 'BOTTOM_COOL_VIA',
      zone: 'RF_RIGHT',
    },
    {
      id: 'CMP_FILTER',
      name: 'RF Filter',
      category: 'Filter',
      qty: 1,
      power_W: 6,
      r_jc: null,
      limit_C: 120,
      limit_type: 'Tc',
      limit_reference_note: 'Center',
      package_type: 'Shielded Module',
      heat_path: 'DirectMetal',
      tim: BUILTIN_TIM_IDS.grease,
      contact: [30, 18],
      tim_blt_mm: 0.05,
      heat_path_parameters: {
        source_model: 'SurfaceBodyBased',
        contact_geometry: 'PerimeterFrame',
        perimeter_land_width_mm: 2,
        exposed_surface_enabled: false,
        exposed_area_mode: 'DerivedPackage',
      },
      template: 'DIRECT_METAL',
      zone: 'RF_LEFT',
    },
    {
      id: 'CMP_FPGA',
      name: 'FPGA',
      category: 'Digital',
      qty: 1,
      power_W: 45,
      r_jc: 0.3,
      limit_C: 125,
      limit_type: 'Tj',
      package_type: 'BGA',
      heat_path: 'Board',
      tim: BUILTIN_TIM_IDS.putty,
      contact: [28, 28],
      template: 'BOTTOM_COOL_VIA',
      zone: 'DIGITAL',
    },
    {
      id: 'CMP_POWER_MODULE',
      name: 'Power Module',
      category: 'Power',
      qty: 1,
      // This is dissipated loss (Pdiss), not the module's rated electrical output.
      power_W: 20,
      r_jc: null,
      limit_C: 115,
      limit_type: 'Ts',
      limit_reference_note: 'Center',
      package_type: 'Module',
      heat_path: 'ModuleSurface',
      tim: BUILTIN_TIM_IDS.grease,
      contact: [58, 26],
      tim_blt_mm: 1,
      template: 'MODULE_SURFACE_TIM',
      zone: 'POWER',
    },
  ]);
}

/** Screen 02 source rows; overlaps by name and includes one additional part. */
export function demoSourceComponents(): Component[] {
  return buildReadyComponents([
    {
      id: 'SRC_FINAL_PA',
      name: 'Final PA',
      category: 'RF',
      qty: 4,
      power_W: 42,
      r_jc: 0.25,
      limit_C: 150,
      limit_type: 'Tj',
      package_type: 'QFN',
      heat_path: 'Coin',
      tim: BUILTIN_TIM_IDS.grease,
      contact: [18, 12],
      template: 'BOTTOM_COOL_COIN',
      zone: 'RF_LEFT',
    },
    {
      id: 'SRC_FPGA',
      name: 'FPGA',
      category: 'Digital',
      qty: 1,
      power_W: 40,
      r_jc: 0.32,
      limit_C: 125,
      limit_type: 'Tj',
      package_type: 'BGA',
      heat_path: 'Board',
      tim: BUILTIN_TIM_IDS.putty,
      contact: [28, 28],
      template: 'BOTTOM_COOL_VIA',
      zone: 'DIGITAL',
    },
    {
      id: 'SRC_LNA',
      name: 'LNA',
      category: 'RF',
      qty: 2,
      power_W: 2,
      r_jc: 0.7,
      limit_C: 110,
      limit_type: 'Tj',
      package_type: 'QFN',
      heat_path: 'Board',
      tim: BUILTIN_TIM_IDS.pad,
      contact: [5, 5],
      template: 'BOTTOM_COOL_VIA',
      zone: 'RF_LEFT',
    },
  ]);
}
