/**
 * Non-confidential synthetic FR1 reference project — 99 §42.
 *
 * This is the component/project side of the Golden Demo. The network,
 * boundary, analytical result and Screens 08–12 artifacts are built from these
 * authoritative inputs in `demoGoldenFlow.ts`.
 */

import type { Project, Scenario } from '@/domain/project';
import { SCHEMA_VERSION } from '@/domain/project';
import {
  emptyExternalMappings,
  emptyThermalSpec,
  type ArchitectureTemplate,
  type BaseZone,
  type Component,
  type ComponentCategory,
  type ComponentProvenance,
  type LimitType,
  type PackageType,
  type TimType,
  type BoardType,
} from '@/domain/component';
import type { SourceRevision } from '@/domain/revision';
import { sourced, type SourcedValue, type ThermalDataSource } from '@/domain/sourcedValue';

export const DEMO_PROJECT_ID = 'FR1_RRU_GOLDEN_DEMO';
export const DEMO_SOURCE_PROJECT_ID = 'FR1_COMPONENT_REFERENCE_DEMO';
export const DEMO_SCENARIO_ID = 'SCN_001';
export const DEMO_NETWORK_ID = 'Main Thermal Network';
export const DEMO_TIMESTAMP = '2026-01-15T08:00:00.000Z';

/** Stable fixture identity makes seeded artifacts reproducible across reloads. */
export const DEMO_SOURCE_REVISION: SourceRevision = {
  project_revision: 'rev:project:golden-demo-v1',
  component_revision: 'rev:component:golden-demo-v1',
  solver_input_revision: 'rev:solver_input:golden-demo-v1',
  limit_revision: 'rev:limit:golden-demo-v1',
  network_revision: 'rev:network:golden-demo-v1',
  scenario_revision: 'rev:scenario:golden-demo-v1',
};

export function demoProject(): Project {
  return {
    project_id: DEMO_PROJECT_ID,
    project_name: 'FR1 RRU Golden Demo',
    revision: DEMO_SOURCE_REVISION.project_revision,
    project_context: {
      customer: 'Synthetic Demo Program',
      owner: 'Thermal Engineering Demo',
      description: 'Non-confidential synthetic FR1 RRU golden-flow validation project',
      product_type: 'RRU',
      deployment: 'Outdoor',
      frequency_range: 'FR1',
      project_stage: 'EVT',
      cooling_architecture: ['Natural Convection', 'Die-casting Fin'],
      enclosure_type: 'Single-sided Cooling',
      notes: [
        'Synthetic engineering fixture only; no customer CAD or test data.',
        'Four thermal zones share one rear heat sink and one ambient boundary.',
        'Analytical results are generated by the product solver during seeding.',
        'FloTHERM remains Deferred and is not required by this workflow.',
      ].join('\n'),
    },
    active_scenario_id: DEMO_SCENARIO_ID,
    status: 'active',
    meta: {
      created_at: DEMO_TIMESTAMP,
      updated_at: DEMO_TIMESTAMP,
      schema_version: SCHEMA_VERSION,
    },
  };
}

export function demoSourceProject(): Project {
  return {
    ...demoProject(),
    project_id: DEMO_SOURCE_PROJECT_ID,
    project_name: 'Synthetic FR1 Component Reference',
    revision: 'rev:project:golden-demo-source-v1',
    active_scenario_id: DEMO_SCENARIO_ID,
    project_context: {
      ...demoProject().project_context,
      description: 'Synthetic component source used to exercise Screen 02 import',
      project_stage: 'Prototype',
      notes: 'Synthetic reference rows with deliberate duplicate names for import testing.',
    },
  };
}

export function demoScenario(projectId = DEMO_PROJECT_ID): Scenario {
  return {
    id: DEMO_SCENARIO_ID,
    project_id: projectId,
    revision:
      projectId === DEMO_PROJECT_ID
        ? DEMO_SOURCE_REVISION.scenario_revision
        : 'rev:scenario:golden-demo-source-v1',
    name: 'Baseline 55C Natural Convection',
    ambient_C: 55,
    wind_mps: 0,
    solar_W_m2: 0,
    power_scale: 1,
    notes: 'Synthetic baseline used by the 01→12 analytical golden flow.',
    is_default: true,
  };
}

function provenance(sourceProjectId: string, sourceProjectName: string): ComponentProvenance {
  return {
    source_type: 'ExistingProject',
    source_project_id: sourceProjectId,
    source_project_name: sourceProjectName,
    source_file: null,
    imported_at: DEMO_TIMESTAMP,
    last_modified_at: DEMO_TIMESTAMP,
    modified_by: 'Golden Demo Seeder',
  };
}

interface Seed {
  id: string;
  name: string;
  category: ComponentCategory;
  qty: number;
  power_W: number;
  r_jc: number;
  limit_C: number;
  limit_type: LimitType;
  package_type: PackageType;
  board_type: BoardType;
  tim: TimType;
  contact: [number, number];
  template: ArchitectureTemplate;
  zone: BaseZone;
}

function demoSourced<T>(value: T, source: ThermalDataSource, reference: string): SourcedValue<T> {
  return {
    ...sourced(value, source, { confidence: 'high', reference }),
    updated_at: DEMO_TIMESTAMP,
  };
}

function buildReadyComponents(seeds: Seed[]): Component[] {
  return seeds.map((seed) => {
    const spec = emptyThermalSpec();
    return {
      id: seed.id,
      name: seed.name,
      category: seed.category,
      enabled: true,
      qty: seed.qty,
      power_W: demoSourced(seed.power_W, 'Imported', 'Synthetic FR1 Golden Demo power budget'),
      thermal_spec: {
        ...spec,
        limit_type: seed.limit_type,
        // The demo's limits come from (synthetic) datasheets, so the surface
        // they refer to is known rather than inferred.
        limit_type_confirmed: true,
        limit_C: demoSourced(seed.limit_C, 'Datasheet', 'Synthetic component qualification limit'),
        r_jc_C_per_W: demoSourced(seed.r_jc, 'Datasheet', 'Synthetic component thermal profile'),
        package_type: seed.package_type,
        geometry: {
          ...spec.geometry,
          package_L_mm: seed.contact[0] + 2,
          package_W_mm: seed.contact[1] + 2,
          package_H_mm: 2,
          contact_L_mm: seed.contact[0],
          contact_W_mm: seed.contact[1],
          pad_L_mm: seed.contact[0],
          pad_W_mm: seed.contact[1],
          board_thickness_mm: 1.6,
        },
        board_path: { type: seed.board_type, parameters: {} },
        tim: {
          ...spec.tim,
          type: seed.tim,
          inheritance: 'component',
          k_W_mK: demoSourced(3, 'Datasheet', 'Synthetic TIM data sheet'),
          thickness_mm: demoSourced(0.15, 'Datasheet', 'Synthetic TIM data sheet'),
        },
      },
      architecture_prep: {
        template_preference: seed.template,
        preferred_base_zone: seed.zone,
        qty_model_preference: seed.qty > 1 ? 'INDIVIDUAL' : 'AGGREGATE',
        thermal_profile_status: 'Ready',
      },
      provenance: provenance(DEMO_SOURCE_PROJECT_ID, 'Synthetic FR1 Component Reference'),
      external_mappings: emptyExternalMappings(),
      notes: 'Synthetic Golden Demo component.',
    };
  });
}

/** Exact 99 §42 population: 4 PA, 4 Driver, 1 Filter, 1 FPGA, 1 Power Module. */
export function demoComponents(): Component[] {
  return buildReadyComponents([
    {
      id: 'CMP_FINAL_PA',
      name: 'Final PA',
      category: 'RF',
      qty: 4,
      power_W: 45,
      r_jc: 0.22,
      limit_C: 150,
      limit_type: 'Tj',
      package_type: 'QFN',
      board_type: 'Copper Coin',
      tim: 'Grease',
      contact: [18, 12],
      template: 'BOTTOM_COOL_COIN',
      zone: 'RF Left',
    },
    {
      id: 'CMP_DRIVER',
      name: 'Driver',
      category: 'RF',
      qty: 4,
      power_W: 8,
      r_jc: 0.55,
      limit_C: 140,
      limit_type: 'Tj',
      package_type: 'QFN',
      board_type: 'Thermal Via',
      tim: 'Pad',
      contact: [8, 8],
      template: 'BOTTOM_COOL_VIA',
      zone: 'RF Right',
    },
    {
      id: 'CMP_FILTER',
      name: 'RF Filter',
      category: 'Filter',
      qty: 1,
      power_W: 6,
      r_jc: 0.8,
      limit_C: 120,
      limit_type: 'Tc',
      package_type: 'Shielded Module',
      board_type: 'Direct Metal',
      tim: 'Pad',
      contact: [30, 18],
      template: 'DIRECT_METAL',
      zone: 'RF Left',
    },
    {
      id: 'CMP_FPGA',
      name: 'FPGA',
      category: 'Digital',
      qty: 1,
      power_W: 45,
      r_jc: 0.3,
      limit_C: 125,
      limit_type: 'Tj',
      package_type: 'BGA',
      board_type: 'Thermal Via',
      tim: 'Putty',
      contact: [28, 28],
      template: 'BOTTOM_COOL_VIA',
      zone: 'Digital',
    },
    {
      id: 'CMP_POWER_MODULE',
      name: 'Power Module',
      category: 'Power',
      qty: 1,
      power_W: 20,
      r_jc: 0.4,
      limit_C: 115,
      limit_type: 'Tc',
      package_type: 'Module',
      board_type: 'Direct Metal',
      tim: 'Grease',
      contact: [24, 20],
      template: 'DIRECT_METAL',
      zone: 'Power',
    },
  ]);
}

/** Screen 02 source rows; overlaps by name and includes one additional part. */
export function demoSourceComponents(): Component[] {
  return buildReadyComponents([
    {
      id: 'SRC_FINAL_PA',
      name: 'Final PA',
      category: 'RF',
      qty: 4,
      power_W: 42,
      r_jc: 0.25,
      limit_C: 150,
      limit_type: 'Tj',
      package_type: 'QFN',
      board_type: 'Copper Coin',
      tim: 'Grease',
      contact: [18, 12],
      template: 'BOTTOM_COOL_COIN',
      zone: 'RF Left',
    },
    {
      id: 'SRC_FPGA',
      name: 'FPGA',
      category: 'Digital',
      qty: 1,
      power_W: 40,
      r_jc: 0.32,
      limit_C: 125,
      limit_type: 'Tj',
      package_type: 'BGA',
      board_type: 'Thermal Via',
      tim: 'Putty',
      contact: [28, 28],
      template: 'BOTTOM_COOL_VIA',
      zone: 'Digital',
    },
    {
      id: 'SRC_LNA',
      name: 'LNA',
      category: 'RF',
      qty: 2,
      power_W: 2,
      r_jc: 0.7,
      limit_C: 110,
      limit_type: 'Tj',
      package_type: 'QFN',
      board_type: 'Thermal Via',
      tim: 'Pad',
      contact: [5, 5],
      template: 'BOTTOM_COOL_VIA',
      zone: 'RF Left',
    },
  ]);
}
